# Adding service for Catalogue
# We are taking ClusterIP service as this communicate with internal POD's only
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    tier: backend
    project: roboshop
    component: catalogue

spec:
  selector:
    # selecting mongodb pod based on the below labels and add to the service
    tier: backend
    project: roboshop
    component: catalogue
  ports:
    - protocol: TCP
      port: 8080          # service port
      targetPort: 8080    # container port